package com.aitchn.prism.api.protection;

public enum ProtectionAction {
    PLACE_CUSTOM_BLOCK,
    BREAK_CUSTOM_BLOCK,
    INTERACT_CUSTOM_BLOCK,
    FORM_STRUCTURE,
    USE_STRUCTURE,
    MODIFY_STRUCTURE,
    MACHINE_INPUT,
    MACHINE_OUTPUT,
    AREA_BREAK,
    ENVIRONMENTAL_DAMAGE,
    PLACE_CONDUIT,
    BREAK_CONDUIT,
    TRANSFORM_BLOCK,
    MODIFY_BLOCK_STATE, DAMAGE_ENTITY, HEAL_ENTITY, MODIFY_ENTITY_STATE, SPAWN_ENTITY,
    ENTITY_DEATH, DROP_ITEM, PICK_BLOCK, RECOVER_AMMUNITION, MODIFY_ITEM_STATE,
    GUIDE_GRANT, RESEARCH, MODIFY_PROGRESS, PROCESS_MACHINE, PORTABLE_PROCESS, DISPOSE_ITEM, FISHING_CATCH, CRAFT_SPECIMEN
}
