package com.aitchn.prism.api.input;

/** Semantic observations, never physical key codes. @since 3.25 */
public enum InputSource {
    LOOK, MOVEMENT, JUMP, SNEAK, SPRINT, ATTACK_ENTITY, SWING, STAB,
    USE_REQUEST, USE_RELEASE, USE_STATE, INTERACT_BLOCK, INTERACT_ENTITY, DIG,
    SWAP_HANDS, HOTBAR_SELECT, DROP, CONTAINER_CLICK, CONTAINER_BUTTON, CONTAINER_CLOSE,
    VEHICLE_MOVE, BOAT_PADDLES, RIDING_JUMP, PLAYER_COMMAND, LIFECYCLE
}
