package com.aitchn.prism.api.input;

public enum InputResetReason {
    TELEPORT, DEATH, RESPAWN, WORLD_CHANGE, CONTEXT_CHANGE, CONTAINER_CHANGE,
    SLOT_CHANGE, HAND_SWAP, QUEUE_OVERFLOW, INVALID_DATA, DISCONNECT,
    SUBSCRIPTION_CLOSED, OWNER_DISABLED, SERVICE_STOPPED, SERVICE_FAILURE, CALLBACK_FAILURE, RETIRED,
    SERVER_VIEW_CORRECTION
}
